#!/usr/bin/env bash
# Refresh .claude/ from the repo's own source-of-truth directories.
#
# .claude/rules/ and .claude/skills/ are byte-for-byte copies of
# global-claude-md/rules/ and skill-toolkit/skills/. They are copies rather
# than symlinks because Claude Code discovers project skills and rules by
# walking .claude/, and because a symlink would not survive a fresh clone into
# an ephemeral cloud container.
#
# Run this after rebasing this branch onto main, whenever the source dirs move
# ahead. It only touches .claude/rules and .claude/skills; CLAUDE.md is a hand
# adaptation (paths repointed, PowerShell rules dropped) and is NEVER
# regenerated — reconcile it by hand against global-claude-md/CLAUDE.md and
# update the deltas table at its end.
#
# --check exits 1 on drift without writing anything, for use in a gate.
#
# --gate audits tools/share_gate.py's verdict on this branch. That gate is
# EXPECTED to fail here and must not be silenced: its [S] rule ("tracked path
# contains /.claude/") is the control enforcing the promise ADOPTERS.md makes to
# anyone who clones this repo, and this branch overrides that promise knowingly.
# Editing the gate or the manifest to make red go green would remove the control
# that protects main. So instead this mode pins the SHAPE of the expected
# failure: every finding must be either the .claude/ policy rule, or one of the
# worked-example paths already reviewed and [[allow]]-ed at its
# skill-toolkit/skills/ original (the allow entries are keyed to exact file
# paths, so the copy under .claude/skills/ is not covered by them). A finding of
# any other shape is a REAL one that this branch introduced — that is the signal
# this mode exists to keep visible across rebases.

set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$repo_root"

src_rules="global-claude-md/rules"
src_skills="skill-toolkit/skills"
dst_rules=".claude/rules"
dst_skills=".claude/skills"

for d in "$src_rules" "$src_skills"; do
    if [ ! -d "$d" ]; then
        echo "error: source directory missing: $d" >&2
        exit 2
    fi
done

if [ "${1:-}" = "--gate" ]; then
    out="$(python3 tools/share_gate.py 2>&1 || true)"
    # Findings are "  [X] <path>:<line>" lines; anything not matching the two
    # known-benign shapes is a real finding this branch introduced.
    unexpected="$(printf '%s\n' "$out" \
        | grep -E '^[[:space:]]*\[[A-Z]\] ' \
        | grep -vE '^[[:space:]]*\[S\] \.claude/' \
        | grep -vE '^[[:space:]]*\[L\] \.claude/skills/(config-self-audit/(SKILL\.md|references/telemetry\.md)|literature-search-extract/scripts/zotero_ris_export\.py):' \
        || true)"
    policy=$(printf '%s\n' "$out" | grep -cE '^[[:space:]]*\[S\] \.claude/' || true)
    shadowed=$(printf '%s\n' "$out" | grep -cE '^[[:space:]]*\[L\] \.claude/' || true)
    echo "expected-red audit of tools/share_gate.py"
    echo "  [S] .claude/ publishing-policy findings : $policy (expected: one per tracked file under .claude/)"
    echo "  [L] allow-shadowed worked examples      : $shadowed (expected: 7)"
    if [ -n "$unexpected" ]; then
        echo
        echo "UNEXPECTED findings — these are real and this branch introduced them:"
        printf '%s\n' "$unexpected"
        exit 1
    fi
    echo "  unexpected findings                     : 0"
    echo "OK: gate is red for the designed reason only."
    exit 0
fi

if [ "${1:-}" = "--check" ]; then
    status=0
    for pair in "$src_rules:$dst_rules" "$src_skills:$dst_skills"; do
        src="${pair%%:*}"
        dst="${pair##*:}"
        if [ ! -d "$dst" ]; then
            echo "DRIFT: $dst does not exist"
            status=1
        elif ! diff -r "$src" "$dst" >/dev/null 2>&1; then
            echo "DRIFT: $dst differs from $src"
            diff -rq "$src" "$dst" || true
            status=1
        else
            echo "ok: $dst matches $src"
        fi
    done
    exit "$status"
fi

# Mirror, so a file deleted at the source disappears here too. rsync is not
# guaranteed present in the container image, so rebuild the trees instead.
rm -rf "$dst_rules" "$dst_skills"
mkdir -p "$dst_rules" "$dst_skills"
cp -a "$src_rules/." "$dst_rules/"
cp -a "$src_skills/." "$dst_skills/"

echo "rules:  $(find "$dst_rules" -type f | wc -l) files"
echo "skills: $(find "$dst_skills" -mindepth 1 -maxdepth 1 -type d | wc -l) dirs, $(find "$dst_skills" -type f | wc -l) files"
echo
echo "Reminder: CLAUDE.md is NOT regenerated by this script. If"
echo "global-claude-md/CLAUDE.md changed, reconcile the root CLAUDE.md by hand."
